pipeline{
	agent none
	stages{
		stage('Build'){
			agent{
				docker{
					image 'python:2.7.16-slim'
				}
			}	
			when{
				changeset '**/vote/**'
			}
			steps{
				echo 'Install python packages'
				dir('vote'){
					sh 'pip install -i requirements.txt'
				}
			}
		}
		stage('Test'){
			agent{
				docker{
					image 'python:2.7.16-slim'
				}
			}	
			when{
				changeset "**/vote/**"
			}
			steps{
				echo 'Execute unit tests'
				sh 'nosetests -v'
				}
		}
		stage('Docker Build''){
			agent any
			when{
				changeset "**/vote/**"
				branch "master"
			}
			steps{
				script{
					docker.withRegistry('', 'dockerlogin'){
						def voteImage = docker.build('initcron/vote:v${env.BUILD_ID}', './vote/')
						voteImage.push('${env.BRANCH_NAME}")
					}	
				}
			}
		}			
	}
		
	post{
		always{
			echo 'blabla'
		}
		failure{
			echo 'Pipeline fails'
		}
		success{
			echo 'Pipeline succeeds'
		}
	}
}
