pipeline{
	agent{
		docker{ image 'maven:3.6.1-jdk-8-alpine'
				   args '-v $HOME/.m2:/root/.m2'
		}
	}
	stages{
		stage('build'){
			when{
				changeset "**/worker/**"
			}
			steps{
				echo "Compilin worker app"
				dir("worker'"){
					sh 'mvn compile'
				}
			}
		}
		stage('test'){
			when{
				changeset "**/worker/**"
			}
			steps{
				echo 'Running unit tests'
				dir('worker'){
					sh 'mvn clean test'
				}
			}
		}
		stage('package'){
			when{
				branch 'master'
			}
			steps{
				echo 'packaging the app'
				dir('worker'){
					sh 'mvn package -DskipTests'
					archiveArtifacts artifacts: '**/target/*.jar'n fingerprint: true
				}
			}
		}
	}
	post{
		always{
			echo 'Pipeline for worker is complete'
		}
		failure{
			slackSend (channel:'')
		}
		success{
			slackSend (channel:'')
		}
	}
		
}
